name: AdShare Proxy server testing
run-name: ${{ github.actor }} is testing out AdShare Proxy servers to check if they are not breaking!
# Run testing workflow on each commit(s) push to repo
on:
  push
  
jobs: 
  test-proxy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    
    - name: Install proxy dependencies
      run: npm install
      working-directory: .
    
    - name: Test proxy
      run: npm test
      working-directory: .