name: Deploy Proxy Server
run-name: ${{ github.actor }} is deploying AdShare Proxy to some provider(s)!

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
        - 'proxy-v**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  proxy-tests:
    # https://stackoverflow.com/a/71489231
    uses: ./github/workflows/proxy-test.yml

  deploy-on-render:
    # Only deploy if the build and test job from the proxy-test workflow completes successfully
    needs: proxy-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Trigger Deploy to Render
        # Need wrapper for curl...
        uses: wei/curl@v1.1.1
        env:
          # https://render.com/docs/deploy-hooks
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        with:
          # wont work if the service is suspended... (409 error)
          args: -X POST $RENDER_DEPLOY_HOOK
        #run: curl -X POST $RENDER_DEPLOY_HOOK
