name: Publish Proxy Server
run-name: ${{ github.actor }} is publishing AdShare Proxy Image to some Docker registry(ies)!

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
        - 'proxy-v**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}  

jobs:

  proxy-tests:
    uses: ./.github/workflows/proxy-test.yml

  publish-image-GHCR:
    # Only publish image if the build and test job from the proxy-test workflow completes successfully
    needs: proxy-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/marketplace/actions/docker-login#github-container-registry
      - name: Sign in @ ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        # tags + labels
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=auto
          # match the tag image with regex pattern; expected tag format = proxy-va.b.c
          tags: type=match,pattern=proxy-v(\d.\d.\d),group=1
          # similar to images: bgunson/as-proxy
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build + Push image with Buildx
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}, latest
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max